version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data-jspdemo:/opt/oracle/oradata
      - ./databse/init_dev/oracle-init-user:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  oracle-data-jspdemo:
