spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: leaderboard
    password: testPassword
    driver-class-name: oracle.jdbc.OracleDriver


# 讓 spring boot run 顯示更多 log 除錯
logging:
  level:
    org:
      springframework:
        boot:
          web:
            servlet: DEBUG
      apache:
        catalina: DEBUG
        tomcat: DEBUG