spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_servelet_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei
    username: seashell
    password: 147
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        boot:
          web:
            servlet: DEBUG
      apache:
        catalina: DEBUG
        tomcat: DEBUG